name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]

jobs:
    skip_ci:
        runs-on: ubuntu-latest
        # Map the output to the job's outputs
        outputs:
            canSkip: ${{ steps.check.outputs.canSkip }}
        steps:
            - id: check
              uses: Legorooj/skip-ci@main

    build:
        name: Check for Successful Build
        timeout-minutes: 15
        runs-on: ubuntu-latest
        needs: [skip_ci]
        if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm build

    # eslint:
    #     name: Check Formatting
    #     timeout-minutes: 15
    #     runs-on: ubuntu-latest
    #     needs: [skip_ci]
    #     if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
    #     steps:
    #         - name: Check out code
    #           uses: actions/checkout@v3

    #         - name: Setup
    #           uses: ./.github/actions/setup

    #         - name: Run ESLint
    #           uses: sibiraj-s/action-eslint@v2
    #           with:
    #               eslint-args: "--quiet"
    #               extensions: "js,jsx,ts,tsx"
    #               annotations: true
