name: "Label Previous Pull Requests"
on:
    workflow_dispatch:

jobs:
    triage:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            # Label PRs 1, 2, and 3
            - uses: actions/labeler@v4
              with:
                  pr-number: |
                      1
                      2
                      3
                      4
                      5
                      6
                      7
                      8
                      9
                      10
                      11
                      12
                      13
                      14
                      15
